{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Packet Loss Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_packet_loss_rate{target=\"google.com\"}",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "ping_packet_loss_rate{target=\"baidu.com\"}",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "ping_packet_loss_rate{target=\"twitter.com\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ping_latency_avg", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Round Trip Time google.com (Avg, Min, Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "ping_latency_min{target=\"google.com\"}",
     "legendFormat": "Minimum {{target}}"
    },
    {
     "expr": "ping_latency_avg{target=\"google.com\"}",
     "legendFormat": "Average {{target}}"
    },
    {
     "expr": "ping_latency_max{target=\"google.com\"}",
     "legendFormat": "Maximum {{target}}"
    }
   ]
  },
  {
   "title": "Packet Loss Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "ping_packet_loss_count", "legendFormat": "{{target}}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}